USE sakila;
SHOW TABLES;

#1 List the number of films per category.

DESCRIBE category;
DESCRIBE film_category;

SELECT c.name AS category,
       COUNT(fc.film_id) AS number_of_films
FROM category AS c
JOIN film_category AS fc
  ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY number_of_films DESC;

#2 Retrieve the store ID, city, and country for each store.

DESCRIBE store;
DESCRIBE city;
DESCRIBE country;

SELECT s.store_id,
       ci.city,
       co.country
FROM store AS s
JOIN address AS a  ON s.address_id = a.address_id
JOIN city    AS ci ON a.city_id    = ci.city_id
JOIN country AS co ON ci.country_id = co.country_id;

#3 Calculate the total revenue generated by each store.

DESCRIBE payment;
DESCRIBE rental;

SELECT i.store_id,
       SUM(p.amount) AS total_revenue
FROM payment   AS p
JOIN rental    AS r ON p.rental_id    = r.rental_id
JOIN inventory AS i ON r.inventory_id = i.inventory_id
GROUP BY i.store_id
ORDER BY total_revenue DESC;

#4 Determine the average running time of films for each category.

DESCRIBE category;
DESCRIBE film category;
DESCRIBE film;

SELECT c.name AS category,
       ROUND(AVG(f.length), 2) AS avg_length_minutes
FROM category AS c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN film          AS f  ON fc.film_id    = f.film_id
GROUP BY c.category_id, c.name
ORDER BY avg_length_minutes DESC;